### ISSUE TITLE
Скачивает только часть доски

### ISSUE THREAD

**Issue by yuri25** [Pmmlabs/PinCrawl#1]
Скачивает из 2188 изображений только 246. Windows 10 -x64.

**Comment by Pmmlabs** [comment]
Укажи имя проблемного аккаунта.
Для аккаунта "myuser" всё работает, проверил.

**Comment by yuri25** [comment]
https://www.pinterest.ru/yuran25/%D0%B3%D0%BE%D1%82%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%B8%D0%B5-%D0%B4%D0%B5%D0%B2%D1%83%D1%88%D0%BA%D0%B8/

**Comment by yuri25** [comment]
Вот мой аккаунт https://www.pinterest.ru/yuran25/   
Там есть доска под номером 3, в ней порядка 2200 картинок, попробуй скачать ее.

**Comment by Pmmlabs** [comment]
Проверил, да, проблема действительно есть, видимо Pinterest перестал выдавать больше одной страницы. Размер страницы выставить больше 250 нельзя - тогда не возвращается вообще ничего. Возможно, теперь получить все изображения с доски можно, только авторизовавшись, но я не планирую добавлять в свою программу функцию авторизации.
Может быть, найдется способ получения всех изображений, поищу в интернете.

**Comment by Mrakobes666** [comment]
Друган, умоляю - добавь авторизацию, или еще чего покрути там в своем коде, я ужасно страдаю без этого ПинКравла!

**Comment by Pmmlabs** [comment]
Исправлено в версии 1.2.5
